### ISSUE TITLE
Clear Preview не работает

### ISSUE THREAD

**Issue by pukhalski** [webnotbombs/hub#2]
Невозможно убрать превью от embed.ly.

**Comment by buduguru** [comment]
Хреново. Будем фиксить

**Comment by buduguru** [comment]
Проверил сейчас - работает (ничего не фиксил)
Посмотри у себя. Если все ок - закрывай.

Надо бы сделать добавление своих превьюшек через загрузку (добавлю issue)

**Comment by pukhalski** [comment]
У меня все равно не работает.

**Comment by buduguru** [comment]
Вот сейчас еще проверил - убирается. Убрал так раньше у поста о wth

**Comment by buduguru** [comment]
т.к. мы убрали функционал embed.ly в новом дизайне, то надобности в решении отпадает
