### ISSUE TITLE
Перевод

### ISSUE THREAD

**Issue by pukhalski** [webnotbombs/hub#4]
Допереводить сайт и сделать PR в Telescope.

**Comment by buduguru** [comment]
Добавил переводы, в том числе к отдельным плагинам, пофиксил старые. 

Поспешил и создал нов. issue https://github.com/webnotbombs/hub/issues/10 , поэтому эту закроем и продолжим фиксить там. PR пока не делал. Сделаем позже как только выловим все косяки.
