### ISSUE TITLE
Очистка поиска

### ISSUE THREAD

**Issue by wild-valcom** [webnotbombs/hub#6]
Очистка поля поиска через ctrl+a > backspace не работает, возвращается старое значение.

Шаги для воспроизведения:
1) Осуществить поиск
2) выделить весь текст в поле поиска и нажать кнопку backspace

**Comment by buduguru** [comment]
Да, подтверждаю

**Comment by buduguru** [comment]
Поиск дальше обсуждаем здесь https://github.com/webnotbombs/hub/issues/14
